const express = require("express");
const bodyParser = require("body-parser");
const app = express();
const adminRouter = require("./routes/admin");
const userRouter = require("./routes/user");
const cors = require("cors");

// Middleware for parsing request bodies
app.use(cors());
app.use(bodyParser.json());
app.use("/admin", adminRouter);
app.use("/user", userRouter);
// app.use("/data", (req,res)=>{
//     res.send([
//         {
//           "reason_code": "TEST1",
//           "category": "business",
//           "metadata": {
//             "reasons": [
//               "test reason 1"
//             ]
//           }
//         },
//         {
//           "reason_code": "TEST2",
//           "category": "business",
//           "metadata": {
//             "reasons": [
//               "test reason 2"
//             ]
//           }
//         }
//       ]);
// })

app.use("/data1", (req, res) => {
  const arr = {
    data: [
      {
        ou_id: "njahdjhsa1",
        name: "kshjkshd",
      },
      {
        ou_id: "njahdjhsa2",
        name: "kshjkshd",
      },
      {
        ou_id: "hshjahbs",
        name: "lkjqksqkshd",
      },
      {
        ou_id: "ijhnkahksj",
        name: "kokijjkshd",
      }
    ],
  };
  res.json(arr);
});

app.use("/data2", (req, res) => {
  const list = [
    {
      Ou_id: "abc",
      public_id: "121",
      name: "jkwhjs",
      package: {
        data: "Hello1",
      },
    },
    {
      Ou_id: "abc",
      public_id: "121",
      name: "jkwhjs",
      package: {
        data: "Hello2",
      },
    },
    {
      Ou_id: "xyz",
      public_id: "121",
      name: "jkwhjs",
      package: {
        data: "Hello3",
      },
    },
    {
      Ou_id: "xyz",
      public_id: "131",
      name: "kljljkwhjs",
      package: {
        data: "Hello3",
      },
    },
    {
      Ou_id: "xyz",
      public_id: "141",
      name: "hjkhjkwhjs",
      package: {
        data: "Hello3",
      },
    },
  ];

  res.json(list);
});

app.use("/data3", (req, res) => {
  const list = {
    data: {
      package: {
        active: true,
        allow_recapture: true,
        "api_only?": true,
        assisted_vkyc_configuration: {
          capture: [
            [
              {
                artifacts: [],
                tasks: [
                  {
                    artifacts: [],
                    task_key: "sec_key1",
                    task_type: "verify.security_question",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: null,
                      fact_type_key: null,
                      help_text: null,
                      label: "Security Question 1",
                      mandatory: false,
                      mark_task_failed_for: [],
                      options: ["Pass", "Fail"],
                      placeholder: null,
                      refs: [
                        {
                          key: "sec_key1:manual_response.question",
                          label: "Question",
                          type: "response_ref",
                        },
                        {
                          key: "sec_key1:manual_response.answer",
                          label: "Expected Answer",
                          type: "response_ref",
                        },
                      ],
                      regex: null,
                      remarks_mandatory_for: ["Fail"],
                      settings: {},
                      side: null,
                      title: null,
                      type: "radio",
                    },
                    template_id: 33637,
                  },
                  {
                    artifacts: [],
                    task_key: "sec_key2",
                    task_type: "verify.security_question",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: null,
                      fact_type_key: null,
                      help_text: null,
                      label: "Security Question 2",
                      mandatory: false,
                      mark_task_failed_for: [],
                      options: ["Pass", "Fail"],
                      placeholder: null,
                      refs: [
                        {
                          key: "sec_key2:manual_response.question",
                          label: "Question",
                          type: "response_ref",
                        },
                        {
                          key: "sec_key2:manual_response.answer",
                          label: "Expected Answer",
                          type: "response_ref",
                        },
                      ],
                      regex: null,
                      remarks_mandatory_for: ["Fail"],
                      settings: {},
                      side: null,
                      title: null,
                      type: "radio",
                    },
                    template_id: 33640,
                  },
                ],
                template: {
                  allow_upload: false,
                  capture_mechanisms: {},
                  category_type: null,
                  detail: "Checks to determine liveness",
                  document_type_key: null,
                  fact_type_key: null,
                  help_text: null,
                  label: null,
                  mandatory: false,
                  mark_task_failed_for: [],
                  options: [],
                  placeholder: null,
                  refs: [],
                  regex: null,
                  remarks_mandatory_for: [],
                  settings: {},
                  side: null,
                  title: "Security checks",
                  type: "card",
                },
                template_id: 33649,
              },
              {
                artifacts: [],
                tasks: [
                  {
                    artifacts: ["nil.nil.location.2.nil"],
                    task_key: "key_location",
                    task_type: "data_capture.location",
                    tasks: [
                      {
                        artifacts: ["nil.nil.location.2.nil"],
                        deps: ["key_location"],
                        task_key: "key_resolve_location",
                        task_type: "resolve.location",
                        template: {
                          allow_upload: false,
                          capture_mechanisms: {},
                          category_type: null,
                          detail: null,
                          document_type_key: null,
                          fact_type_key: null,
                          help_text: null,
                          label: null,
                          mandatory: false,
                          mark_task_failed_for: [],
                          options: [],
                          placeholder: null,
                          refs: [],
                          regex: null,
                          remarks_mandatory_for: [],
                          settings: {},
                          side: null,
                          title: null,
                          type: "hidden",
                        },
                        template_id: 33643,
                      },
                    ],
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: null,
                      fact_type_key: "location",
                      help_text: null,
                      label: "Fetch Users Location",
                      mandatory: true,
                      mark_task_failed_for: [],
                      options: [],
                      placeholder: null,
                      refs: [],
                      regex: null,
                      remarks_mandatory_for: [],
                      settings: {},
                      side: null,
                      title: null,
                      type: "button",
                    },
                    template_id: 33652,
                  },
                ],
                template: {
                  allow_upload: false,
                  capture_mechanisms: {},
                  category_type: null,
                  detail: null,
                  document_type_key: null,
                  fact_type_key: null,
                  help_text: null,
                  label: null,
                  mandatory: false,
                  mark_task_failed_for: [],
                  options: [],
                  placeholder: null,
                  refs: [],
                  regex: null,
                  remarks_mandatory_for: [],
                  settings: {},
                  side: null,
                  title: "Location check",
                  type: "card",
                },
                template_id: 33658,
              },
              {
                artifacts: [],
                tasks: [
                  {
                    artifacts: ["nil.selfie.nil.2.nil"],
                    task_key: "key10",
                    task_type: "data_capture.data_capture",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: "selfie",
                      fact_type_key: null,
                      help_text:
                        "Ask the customer to stay still and look directly into the camera. Ensure face is evenly lit.",
                      label: "Screenshot of Face",
                      mandatory: true,
                      mark_task_failed_for: [],
                      options: ["selfie"],
                      placeholder: null,
                      refs: [
                        {
                          key: "nil.selfie.nil.2.nil",
                          label: "Face Screenshot",
                          type: "artifact",
                        },
                      ],
                      regex: null,
                      remarks_mandatory_for: [],
                      settings: {},
                      side: null,
                      title: null,
                      type: "screenshot",
                    },
                    template_id: 33646,
                  },
                  {
                    artifacts: ["nil.ind_pan.nil.2.nil"],
                    task_key: "key11",
                    task_type: "data_capture.data_capture",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: "ind_pan",
                      fact_type_key: null,
                      help_text:
                        "Ask the customer to place the PAN card on a flat surface. Ask to switch to back camera",
                      label: "PAN Screenshot",
                      mandatory: true,
                      mark_task_failed_for: [],
                      options: ["ind_pan"],
                      placeholder: null,
                      refs: [
                        {
                          key: "nil.ind_pan.nil.2.nil",
                          label: "PAN screenshot",
                          type: "artifact",
                        },
                      ],
                      regex: null,
                      remarks_mandatory_for: [],
                      settings: {},
                      side: null,
                      title: null,
                      type: "screenshot",
                    },
                    template_id: 33650,
                  },
                  {
                    artifacts: [
                      "nil.selfie.nil.2.nil",
                      "nil.ind_pan.nil.2.nil",
                    ],
                    task_key: "key13",
                    task_type: "compare.face_compare",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: null,
                      fact_type_key: null,
                      help_text:
                        "Face screenshot v/s PAN card screenshot. This will get initiated automatically in future",
                      label: "Initiate Face Compare 1",
                      mandatory: true,
                      mark_task_failed_for: [],
                      options: [],
                      placeholder: null,
                      refs: [],
                      regex: null,
                      remarks_mandatory_for: [],
                      settings: {},
                      side: null,
                      title: null,
                      type: "compare.face_compare",
                    },
                    template_id: 33641,
                    validations: [
                      {
                        attr: "key13:automated_response.match_score",
                        attr_type: "response_ref",
                        criteria: [
                          {
                            compare_with: [60],
                            operator: "<=",
                            output: [
                              "Face compare score should NOT be less than 60. Recapture Selfie and reinitiate the check (mandatory)",
                            ],
                          },
                        ],
                        type: "server",
                      },
                    ],
                  },
                  {
                    artifacts: [
                      "nil.ind_pan.nil.2.nil",
                      "nil.nil.name.0.nil",
                      "nil.ind_pan.id_number.0.nil",
                    ],
                    task_key: "key14",
                    task_type: "extract.ind_pan",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: null,
                      fact_type_key: null,
                      help_text: null,
                      label: "Initiate PAN extraction",
                      mandatory: true,
                      mark_task_failed_for: [],
                      options: [],
                      placeholder: null,
                      refs: [],
                      regex: null,
                      remarks_mandatory_for: [],
                      settings: {},
                      side: null,
                      title: null,
                      type: "extract.ind_pan",
                    },
                    template_id: 33645,
                    validations: [
                      {
                        attr: "key14:automated_response.match_output.number",
                        attr_type: "response_ref",
                        criteria: [
                          {
                            compare_with: [5],
                            operator: "!=",
                            output: [
                              "PAN number match score should NOT be less than 5. Recapture PAN and reinitiate the check (mandatory)",
                            ],
                          },
                        ],
                        type: "server",
                      },
                    ],
                  },
                ],
                template: {
                  allow_upload: false,
                  capture_mechanisms: {},
                  category_type: null,
                  detail: null,
                  document_type_key: null,
                  fact_type_key: null,
                  help_text: null,
                  label: null,
                  mandatory: false,
                  mark_task_failed_for: [],
                  options: [],
                  placeholder: null,
                  refs: [],
                  regex: null,
                  remarks_mandatory_for: [],
                  settings: {},
                  side: null,
                  title: "Capture PAN and Selfie",
                  type: "card",
                },
                template_id: 33662,
              },
              {
                artifacts: [],
                tasks: [
                  {
                    artifacts: [],
                    task_key: "key31",
                    task_type: "verify.qa",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: null,
                      fact_type_key: null,
                      help_text: null,
                      label: "Do the names match?",
                      mandatory: true,
                      mark_task_failed_for: [],
                      options: ["Pass", "Fail"],
                      placeholder: null,
                      refs: [
                        {
                          key: "nil.nil.name.0.nil",
                          label: "Name from Bank",
                          type: "artifact",
                        },
                        {
                          key: "key14:automated_response.extraction_output.name_on_card",
                          label: "Name extracted from PAN",
                          type: "response_ref",
                        },
                        {
                          key: "key14:automated_response.match_output.name_on_card",
                          label: "Match score",
                          type: "response_ref",
                        },
                      ],
                      regex: null,
                      remarks_mandatory_for: ["Fail"],
                      settings: {},
                      side: null,
                      title: null,
                      type: "radio",
                    },
                    template_id: 33644,
                  },
                  {
                    artifacts: [],
                    task_key: "key32",
                    task_type: "verify.qa",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: null,
                      fact_type_key: null,
                      help_text: null,
                      label: "Do the PAN numbers match",
                      mandatory: true,
                      mark_task_failed_for: [],
                      options: ["Pass", "Fail"],
                      placeholder: null,
                      refs: [
                        {
                          key: "nil.ind_pan.id_number.0.nil",
                          label: "Number from Bank",
                          type: "artifact",
                        },
                        {
                          key: "key14:automated_response.extraction_output.id_number",
                          label: "Number extracted from PAN",
                          type: "response_ref",
                        },
                        {
                          key: "key14:automated_response.match_output.number",
                          label: "Match score",
                          type: "response_ref",
                        },
                        {
                          key: "key14:validation_error",
                          label: "Number Validation",
                          type: "validation_error",
                        },
                      ],
                      regex: null,
                      remarks_mandatory_for: ["Fail"],
                      settings: {},
                      side: null,
                      title: null,
                      type: "radio",
                    },
                    template_id: 33642,
                  },
                ],
                template: {
                  allow_upload: false,
                  capture_mechanisms: {},
                  category_type: null,
                  detail: null,
                  document_type_key: null,
                  fact_type_key: null,
                  help_text: null,
                  label: null,
                  mandatory: false,
                  mark_task_failed_for: [],
                  options: [],
                  placeholder: null,
                  refs: [],
                  regex: null,
                  remarks_mandatory_for: [],
                  settings: {},
                  side: null,
                  title: "PAN Checks",
                  type: "card",
                },
                template_id: 33653,
              },
              {
                artifacts: [],
                tasks: [
                  {
                    artifacts: [],
                    task_key: "key40",
                    task_type: "verify.qa",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: null,
                      fact_type_key: null,
                      help_text: null,
                      label: "Do the faces match?",
                      mandatory: true,
                      mark_task_failed_for: [],
                      options: ["Pass", "Fail"],
                      placeholder: null,
                      refs: [
                        {
                          key: "nil.selfie.nil.2.nil",
                          label: "Face Screenshot",
                          type: "artifact",
                        },
                        {
                          key: "nil.ind_pan.nil.2.nil",
                          label: "PAN Screenshot",
                          type: "artifact",
                        },
                        {
                          key: "key13:automated_response.match_score",
                          label: "Match score",
                          type: "response_ref",
                        },
                        {
                          key: "key13:validation_error",
                          label: "Face Validation",
                          type: "validation_error",
                        },
                      ],
                      regex: null,
                      remarks_mandatory_for: ["Fail"],
                      settings: {},
                      side: null,
                      title: null,
                      type: "radio",
                    },
                    template_id: 33656,
                  },
                ],
                template: {
                  allow_upload: false,
                  capture_mechanisms: {},
                  category_type: null,
                  detail: null,
                  document_type_key: null,
                  fact_type_key: null,
                  help_text: null,
                  label: null,
                  mandatory: false,
                  mark_task_failed_for: [],
                  options: [],
                  placeholder: null,
                  refs: [],
                  regex: null,
                  remarks_mandatory_for: [],
                  settings: {},
                  side: null,
                  title: "Face checks",
                  type: "card",
                },
                template_id: 33661,
              },
              {
                artifacts: [],
                tasks: [
                  {
                    artifacts: ["nil.wet_signature.nil.2.nil"],
                    task_key: "keywetsign",
                    task_type: "data_capture.data_capture",
                    template: {
                      allow_upload: false,
                      capture_mechanisms: {},
                      category_type: null,
                      detail: null,
                      document_type_key: "wet_signature",
                      fact_type_key: null,
                      help_text:
                        "Ask the customer to place the signature on a flat surface. Ask to switch to back camera. Ensure that the entire signature is captured clearly and horizontally. Signature should neither be captured vertically nor should be distorted/cropped",
                      label: "Screenshot of Wet Signature",
                      mandatory: true,
                      mark_task_failed_for: [],
                      options: ["wet_signature"],
                      placeholder: null,
                      refs: [
                        {
                          key: "nil.wet_signature.nil.2.nil",
                          label: "Screenshot of Wet Signature",
                          type: "artifact",
                        },
                      ],
                      regex: null,
                      remarks_mandatory_for: [],
                      settings: {},
                      side: null,
                      title: null,
                      type: "screenshot",
                    },
                    template_id: 33660,
                  },
                ],
                template: {
                  allow_upload: false,
                  capture_mechanisms: {},
                  category_type: null,
                  detail: null,
                  document_type_key: null,
                  fact_type_key: null,
                  help_text: null,
                  label: null,
                  mandatory: false,
                  mark_task_failed_for: [],
                  options: [],
                  placeholder: null,
                  refs: [],
                  regex: null,
                  remarks_mandatory_for: [],
                  settings: {},
                  side: null,
                  title: "Capture wet signature",
                  type: "card",
                },
                template_id: 33664,
              },
            ],
          ],
          introduction: {
            additional_text:
              "Your information will be used by IDFC First Bank verification ",
            prerequisite_card: {
              box: true,
              prerequisite_items: ["Pan Card"],
              title: "Please ensure you're ready with these",
            },
            title: "Initiate Verification",
          },
          security_question_keys: ["sec_key1", "sec_key2"],
        },
        assisted_vkyc_feature_flags: {},
        assisted_vkyc_reasons: {},
        autoclose_configuration: {},
        "autoclose_enabled?": false,
        capture_configuration: {
          allowed_poa_documents: [],
          allowed_poi_documents: [],
          capture: [[]],
          page_sequence: [
            {
              page: "vkyc.assisted_vkyc",
              validations: [],
            },
          ],
          permissions: {},
          validation_checks: [],
          validation_config: {},
        },
        capture_enabled: true,
        capture_feature_flags: {},
        capture_processing_configuration: {},
        description: null,
        display_name: null,
        generic_page_configuration: {},
        is_generic: false,
        label: "IDFC Savings Account with randomide question",
        locale_config: {
          label: "english",
          locale: "en",
          right_to_left: false,
        },
        metadata: {
          checks: {
            assisted_vkyc: [
              {
                input: ["nil.wet_signature.nil.2.nil"],
                task_key: "keywetsign",
                task_type: "data_capture.data_capture",
              },
              {
                input: [],
                task_key: null,
                task_type: null,
              },
              {
                input: [],
                task_key: "key40",
                task_type: "verify.qa",
              },
              {
                input: [],
                task_key: null,
                task_type: null,
              },
              {
                input: [],
                task_key: "key32",
                task_type: "verify.qa",
              },
              {
                input: [],
                task_key: "key31",
                task_type: "verify.qa",
              },
              {
                input: [],
                task_key: null,
                task_type: null,
              },
              {
                input: [
                  "nil.ind_pan.nil.2.nil",
                  "nil.nil.name.0.nil",
                  "nil.ind_pan.id_number.0.nil",
                ],
                task_key: "key14",
                task_type: "extract.ind_pan",
              },
              {
                input: ["nil.selfie.nil.2.nil", "nil.ind_pan.nil.2.nil"],
                task_key: "key13",
                task_type: "compare.face_compare",
              },
              {
                input: ["nil.ind_pan.nil.2.nil"],
                task_key: "key11",
                task_type: "data_capture.data_capture",
              },
              {
                input: ["nil.selfie.nil.2.nil"],
                task_key: "key10",
                task_type: "data_capture.data_capture",
              },
              {
                input: [],
                task_key: null,
                task_type: null,
              },
              {
                input: ["nil.nil.location.2.nil"],
                task_key: "key_resolve_location",
                task_type: "resolve.location",
              },
              {
                input: ["nil.nil.location.2.nil"],
                task_key: "key_location",
                task_type: "data_capture.location",
              },
              {
                input: [],
                task_key: null,
                task_type: null,
              },
              {
                input: [],
                task_key: "sec_key2",
                task_type: "verify.security_question",
              },
              {
                input: [],
                task_key: "sec_key1",
                task_type: "verify.security_question",
              },
              {
                input: [],
                task_key: null,
                task_type: null,
              },
            ],
            post: [],
            pre: [
              {
                input: [],
                task_key: "vkyc.assisted_vkyc",
                task_type: "vkyc.assisted_vkyc",
              },
            ],
          },
          resources: {
            0: ["nil.ind_pan.id_number.0.nil", "nil.nil.name.0.nil"],
            1: [],
            2: [
              "nil.nil.location.2.nil",
              "nil.selfie.nil.2.nil",
              "nil.ind_pan.nil.2.nil",
              "nil.wet_signature.nil.2.nil",
            ],
            3: [],
            4: [],
          },
        },
        name: "IDFC Savings Account",
        notification_configuration: {},
        post_checks: [],
        pre_checks: [
          {
            artifacts: [],
            task_key: "vkyc.assisted_vkyc",
            task_type: "vkyc.assisted_vkyc",
          },
        ],
        review_configuration: {
          capture: [
            {
              artifacts: ["nil.nil.customer.2.nil", "nil.nil.agent.2.nil"],
              tasks: [
                {
                  tasks: [
                    {
                      tasks: [],
                      template: {
                        allow_upload: false,
                        capture_mechanisms: {},
                        category_type: null,
                        detail: null,
                        document_type_key: null,
                        fact_type_key: null,
                        help_text: null,
                        label: null,
                        mandatory: false,
                        mark_task_failed_for: [],
                        options: [],
                        placeholder: null,
                        refs: [
                          {
                            key: "sec_key1:manual_response.question",
                            label: "Question",
                            type: "response_ref",
                          },
                          {
                            key: "sec_key1:manual_response.answer",
                            label: "Expected Answer",
                            type: "response_ref",
                          },
                          {
                            key: "sec_key1:manual_response.value",
                            label: "Agent response",
                            type: "response_ref",
                          },
                          {
                            key: "sec_key1:manual_response.remarks",
                            label: "Agent Remarks",
                            type: "response_ref",
                          },
                        ],
                        regex: null,
                        remarks_mandatory_for: [],
                        settings: {},
                        side: null,
                        title: "Security Question 1",
                        type: "section",
                      },
                      template_id: 33639,
                    },
                    {
                      tasks: [],
                      template: {
                        allow_upload: false,
                        capture_mechanisms: {},
                        category_type: null,
                        detail: null,
                        document_type_key: null,
                        fact_type_key: null,
                        help_text: null,
                        label: null,
                        mandatory: false,
                        mark_task_failed_for: [],
                        options: [],
                        placeholder: null,
                        refs: [
                          {
                            key: "sec_key2:manual_response.question",
                            label: "Question",
                            type: "response_ref",
                          },
                          {
                            key: "sec_key2:manual_response.answer",
                            label: "Expected Answer",
                            type: "response_ref",
                          },
                          {
                            key: "sec_key2:manual_response.value",
                            label: "Agent response",
                            type: "response_ref",
                          },
                          {
                            key: "sec_key2:manual_response.remarks",
                            label: "Agent Remarks",
                            type: "response_ref",
                          },
                        ],
                        regex: null,
                        remarks_mandatory_for: [],
                        settings: {},
                        side: null,
                        title: "Security Question 2",
                        type: "section",
                      },
                      template_id: 33654,
                    },
                  ],
                  template: {
                    allow_upload: false,
                    capture_mechanisms: {},
                    category_type: null,
                    detail: null,
                    document_type_key: null,
                    fact_type_key: null,
                    help_text: null,
                    label: null,
                    mandatory: false,
                    mark_task_failed_for: [],
                    options: [],
                    placeholder: null,
                    refs: [],
                    regex: null,
                    remarks_mandatory_for: [],
                    settings: {},
                    side: null,
                    title: "Security checks",
                    type: "card",
                  },
                  template_id: 33663,
                },
                {
                  tasks: [
                    {
                      tasks: [],
                      template: {
                        allow_upload: false,
                        capture_mechanisms: {},
                        category_type: null,
                        detail: null,
                        document_type_key: null,
                        fact_type_key: null,
                        help_text: null,
                        label: null,
                        mandatory: false,
                        mark_task_failed_for: [],
                        options: [],
                        placeholder: null,
                        refs: [
                          {
                            key: "nil.nil.location.2.nil:value.latitude",
                            label: "Latitude",
                            type: "artifact",
                          },
                          {
                            key: "nil.nil.location.2.nil:value.longitude",
                            label: "Longitude",
                            type: "artifact",
                          },
                          {
                            key: "nil.nil.location.2.nil:value.address.street_address",
                            label: "Address",
                            type: "artifact",
                          },
                          {
                            key: "nil.nil.location.2.nil:value.accuracy_level",
                            label: "Accuracy",
                            type: "artifact",
                          },
                        ],
                        regex: null,
                        remarks_mandatory_for: [],
                        settings: {},
                        side: null,
                        title: "Location",
                        type: "section",
                      },
                      template_id: 33633,
                    },
                  ],
                  template: {
                    allow_upload: false,
                    capture_mechanisms: {},
                    category_type: null,
                    detail: null,
                    document_type_key: null,
                    fact_type_key: null,
                    help_text: null,
                    label: null,
                    mandatory: false,
                    mark_task_failed_for: [],
                    options: [],
                    placeholder: null,
                    refs: [],
                    regex: null,
                    remarks_mandatory_for: [],
                    settings: {},
                    side: null,
                    title: "Location checks",
                    type: "card",
                  },
                  template_id: 33648,
                },
                {
                  tasks: [
                    {
                      tasks: [],
                      template: {
                        allow_upload: false,
                        capture_mechanisms: {},
                        category_type: null,
                        detail: null,
                        document_type_key: null,
                        fact_type_key: null,
                        help_text: null,
                        label: null,
                        mandatory: false,
                        mark_task_failed_for: [],
                        options: [],
                        placeholder: null,
                        refs: [
                          {
                            key: "nil.ind_pan.nil.2.nil",
                            label: "Pan Card screenshot",
                            type: "artifact",
                          },
                          {
                            key: "nil.nil.name.0.nil",
                            label: "Name from Bank",
                            type: "artifact",
                          },
                          {
                            key: "key14:automated_response.extraction_output.name_on_card",
                            label: "Name extracted from PAN",
                            type: "response_ref",
                          },
                          {
                            key: "key31:manual_response.value",
                            label: "Agent Response",
                            type: "response_ref",
                          },
                          {
                            key: "key31:manual_response.remarks",
                            label: "Agent Remarks",
                            type: "response_ref",
                          },
                        ],
                        regex: null,
                        remarks_mandatory_for: [],
                        settings: {},
                        side: null,
                        title: null,
                        type: "section",
                      },
                      template_id: 33638,
                    },
                    {
                      tasks: [],
                      template: {
                        allow_upload: false,
                        capture_mechanisms: {},
                        category_type: null,
                        detail: null,
                        document_type_key: null,
                        fact_type_key: null,
                        help_text: null,
                        label: null,
                        mandatory: false,
                        mark_task_failed_for: [],
                        options: [],
                        placeholder: null,
                        refs: [
                          {
                            key: "nil.ind_pan.id_number.0.nil",
                            label: "Number from Bank",
                            type: "artifact",
                          },
                          {
                            key: "key14:automated_response.extraction_output.id_number",
                            label: "Number extracted from PAN",
                            type: "response_ref",
                          },
                          {
                            key: "key32:manual_response.value",
                            label: "Agent Response",
                            type: "response_ref",
                          },
                          {
                            key: "key32:manual_response.remarks",
                            label: "Agent Remarks",
                            type: "response_ref",
                          },
                        ],
                        regex: null,
                        remarks_mandatory_for: [],
                        settings: {},
                        side: null,
                        title: null,
                        type: "section",
                      },
                      template_id: 33635,
                    },
                  ],
                  template: {
                    allow_upload: false,
                    capture_mechanisms: {},
                    category_type: null,
                    detail: null,
                    document_type_key: null,
                    fact_type_key: null,
                    help_text: null,
                    label: null,
                    mandatory: false,
                    mark_task_failed_for: [],
                    options: [],
                    placeholder: null,
                    refs: [],
                    regex: null,
                    remarks_mandatory_for: [],
                    settings: {},
                    side: null,
                    title: "PAN Checks",
                    type: "card",
                  },
                  template_id: 33651,
                },
                {
                  tasks: [
                    {
                      template: {
                        allow_upload: false,
                        capture_mechanisms: {},
                        category_type: null,
                        detail: null,
                        document_type_key: null,
                        fact_type_key: null,
                        help_text: null,
                        label: null,
                        mandatory: false,
                        mark_task_failed_for: [],
                        options: [],
                        placeholder: null,
                        refs: [
                          {
                            key: "nil.ind_pan.nil.2.nil",
                            label: "PAN Card screenshot",
                            type: "artifact",
                          },
                          {
                            key: "nil.selfie.nil.2.nil",
                            label: "Selfie screenshot",
                            type: "artifact",
                          },
                          {
                            key: "key13:automated_response.match_score",
                            label: "Match Results",
                            type: "response_ref",
                          },
                        ],
                        regex: null,
                        remarks_mandatory_for: [],
                        settings: {},
                        side: null,
                        title: null,
                        type: "section",
                      },
                      template_id: 33634,
                    },
                    {
                      tasks: [],
                      template: {
                        allow_upload: false,
                        capture_mechanisms: {},
                        category_type: null,
                        detail: null,
                        document_type_key: null,
                        fact_type_key: null,
                        help_text: null,
                        label: null,
                        mandatory: false,
                        mark_task_failed_for: [],
                        options: [],
                        placeholder: null,
                        refs: [
                          {
                            key: "key40:manual_response.value",
                            label: "Agent Response",
                            type: "response_ref",
                          },
                          {
                            key: "key40:manual_response.remarks",
                            label: "Agent Remarks",
                            type: "response_ref",
                          },
                        ],
                        regex: null,
                        remarks_mandatory_for: [],
                        settings: {},
                        side: null,
                        title: null,
                        type: "section",
                      },
                      template_id: 33636,
                    },
                  ],
                  template: {
                    allow_upload: false,
                    capture_mechanisms: {},
                    category_type: null,
                    detail: null,
                    document_type_key: null,
                    fact_type_key: null,
                    help_text: null,
                    label: null,
                    mandatory: false,
                    mark_task_failed_for: [],
                    options: [],
                    placeholder: null,
                    refs: [],
                    regex: null,
                    remarks_mandatory_for: [],
                    settings: {},
                    side: null,
                    title: "Face checks",
                    type: "card",
                  },
                  template_id: 33647,
                },
                {
                  tasks: [
                    {
                      tasks: [],
                      template: {
                        allow_upload: false,
                        capture_mechanisms: {},
                        category_type: null,
                        detail: null,
                        document_type_key: null,
                        fact_type_key: null,
                        help_text: null,
                        label: null,
                        mandatory: false,
                        mark_task_failed_for: [],
                        options: [],
                        placeholder: null,
                        refs: [
                          {
                            key: "nil.wet_signature.nil.2.nil",
                            label: "Screenshot of Wet Signature",
                            type: "artifact",
                          },
                        ],
                        regex: null,
                        remarks_mandatory_for: [],
                        settings: {},
                        side: null,
                        title: null,
                        type: "section",
                      },
                      template_id: 33655,
                    },
                  ],
                  template: {
                    allow_upload: false,
                    capture_mechanisms: {},
                    category_type: null,
                    detail: null,
                    document_type_key: null,
                    fact_type_key: null,
                    help_text: null,
                    label: null,
                    mandatory: false,
                    mark_task_failed_for: [],
                    options: [],
                    placeholder: null,
                    refs: [],
                    regex: null,
                    remarks_mandatory_for: [],
                    settings: {},
                    side: null,
                    title: "Wet signature",
                    type: "card",
                  },
                  template_id: 33659,
                },
                {
                  tasks: [
                    {
                      tasks: [],
                      template: {
                        allow_upload: false,
                        capture_mechanisms: {},
                        category_type: null,
                        detail: null,
                        document_type_key: null,
                        fact_type_key: null,
                        help_text: null,
                        label: null,
                        mandatory: false,
                        mark_task_failed_for: [],
                        options: [],
                        placeholder: null,
                        refs: [
                          {
                            key: "vkyc.assisted_vkyc:manual_response.status",
                            label: "Agent marked this profile as",
                            type: "response_ref",
                          },
                          {
                            key: "vkyc.assisted_vkyc:manual_response.status_reason",
                            label: "Agent rejected because",
                            type: "response_ref",
                          },
                        ],
                        regex: null,
                        remarks_mandatory_for: [],
                        settings: {},
                        side: null,
                        title: null,
                        type: "section",
                      },
                      template_id: 33657,
                    },
                  ],
                  template: {
                    allow_upload: false,
                    capture_mechanisms: {},
                    category_type: null,
                    detail: null,
                    document_type_key: null,
                    fact_type_key: null,
                    help_text: null,
                    label: null,
                    mandatory: false,
                    mark_task_failed_for: [],
                    options: [],
                    placeholder: null,
                    refs: [],
                    regex: null,
                    remarks_mandatory_for: [],
                    settings: {},
                    side: null,
                    title: "Agent marked this profile as",
                    type: "card",
                  },
                  template_id: 33665,
                },
              ],
              template: {
                allow_upload: false,
                capture_mechanisms: {},
                category_type: null,
                detail: null,
                document_type_key: null,
                fact_type_key: null,
                help_text: null,
                label: null,
                mandatory: false,
                mark_task_failed_for: [],
                options: [],
                placeholder: null,
                refs: [],
                regex: null,
                remarks_mandatory_for: [],
                settings: {
                  div: "assisted",
                },
                side: null,
                title: "Assisted Video KYC",
                type: "div",
              },
              template_id: 33666,
            },
          ],
        },
        review_configuration_reasons: {},
        review_enabled: true,
        self_video_feature_flags: {},
        self_vkyc_configuration: {},
        theme: {
          v1: null,
          v2: null,
        },
        version: "v1.1",
      },
    },
  };

  res.json(list);
});

app.use("/data4", (req, res) => {
  const templateId= req.query.templateId
  console.log(templateId);
  const templates = {
    33649: {
        allow_upload: false,
        capture_mechanisms: {},
        category_type: null,
        detail: null,
        document_type_key: null,
        fact_type_key: null,
        help_text: null,
        id: 33649,
        label: null,
        mandatory: false,
        mark_task_failed_for: [],
        options: [],
        placeholder: null,
        refs: [],
        regex: null,
        remarks_mandatory_for: [],
        settings: {},
        side: null,
        title: null,
        type: "hidden",
    },
    33653: {
        allow_upload: false,
        capture_mechanisms: {},
        category_type: null,
        detail: null,
        document_type_key: null,
        fact_type_key: null,
        help_text: null,
        label: null,
        id: 33653,
        mandatory: false,
        mark_task_failed_for: [],
        options: [],
        placeholder: null,
        refs: [],
        regex: null,
        remarks_mandatory_for: [],
        settings: {},
        side: null,
        title: null,
        type: "hidden",
      },
  };

  res.json({data:templates[templateId]});
});

const PORT = 5000;

app.get("/", (req, res) => {
  res.send("Hello World");
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
